# Simple, clean prompt with Joker-inspired purple and green colors

# Format of the prompt
format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character
"""

# Set a custom prompt character
[character]
success_symbol = "[➜](bold #8A2BE2)"  # Bright purple
error_symbol = "[✗](bold #FF3131)"    # Bright red for errors

# Directory display
[directory]
style = "bold #50C878"                # Emerald green
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
home_symbol = " ~"

# Git branch display
[git_branch]
style = "bold #8A2BE2"                # Bright purple
symbol = " "
format = "[$symbol$branch]($style) "

# Git status indicators
[git_status]
style = "#50C878"                     # Emerald green
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

# Command duration
[cmd_duration]
min_time = 2000                       # Show for commands that took more than 2s
format = " took [$duration]($style)"
style = "italic #8A2BE2"              # Italic purple

# Disable unnecessary modules to keep it clean
[aws]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

[status]
disabled = false
format = '[$status]($style) '
style = 'bold red'

[swift]
disabled = true

[terraform]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
