[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = true
show_always = false

[hostname]
ssh_only = false
format = '[$hostname](bold red) '
trim_at = "."
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 5000
format = 'took [$duration](bold yellow)'

[aws]
disabled = true

[buf]
symbol = " "
disabled = true

[c]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[crystal]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true
[directory]
read_only = " 󰌾"
home_symbol = " ~"

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[fennel]
symbol = " "
disabled = true

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[haxe]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
symbol = " "
disabled = true

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = true

[meson]
symbol = "󰔷 "
disabled = true

[nim]
symbol = "󰆥 "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[ocaml]
symbol = " "
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[pijul_channel]
symbol = " "
disabled = true

[python]
symbol = " "

[rlang]
symbol = "󰟔 "
disabled = true

[ruby]
symbol = " "

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[swift]
symbol = " "
disabled = true

[zig]
symbol = " "
disabled = true
